disabled_rules:
  - colon
  - comma
  - control_statement
  - force_cast
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - missing_docs

excluded: 
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

included: 
  - WidgetsApp
  - WidgetsAppKeyboard
  - WidgetsAppTests

file_length:
  warning: 500
  error: 600

reporter: xcode

warning_threshold: 15
