disabled_rules:
  - colon
  - comma
  - control_statement
  - cyclomatic_complexity
  - vertical_parameter_alignment

opt_in_rules:
  - empty_count
  - missing_docs
  - force_unwrapping

excluded: 
  - Carthage
  - Pods

included: 
  - WidgetsApp
  - WidgetsAppKeyboard
  - WidgetsAppTests

file_length:
  warning: 500
  error: 600

force_cast:
force_try:
missing_docs:
  warning:
  - internal
  - open
  - public
  
line_length:
  warning: 150
  
reporter: xcode

warning_threshold: 50
